language: java
jdk: openjdk12
deploy:
  provider: heroku
  api-key:
    secure: $HEROKU_API_KEY
  app: impurity-online-twitch-service
addons:
  sonarcloud:
    organization: "tmk2003-github"
    token:
      secure: "$SONAR_TOKEN"
before_install:
  - chmod +x gradlew
script:
  - ./gradlew sonarqube